export enum SeguimientoEnum {
  RECHAZADO = -1,
  LISTO_PARA_APROBAR = 0,
  ESPERANDO_APROBACION = 1,
  LISTO_PARA_ABONAR = 2,
  EN_CURSO = 3,
  FINALIZADO = 4,
  ENVIADO = 5,
  LISTO_PARA_RETIRAR = 6,
  ENTREGADO = 7,
  CERRADO = 8,
}
